/*
 * This file is generated by jOOQ.
*/
package com.origins.domain;


import com.origins.DefaultCatalog;
import com.origins.domain.tables.Availabilities;
import com.origins.domain.tables.Categories;
import com.origins.domain.tables.Migrations;
import com.origins.domain.tables.PasswordResets;
import com.origins.domain.tables.Permissions;
import com.origins.domain.tables.Reservations;
import com.origins.domain.tables.Resources;
import com.origins.domain.tables.RoleHasPermissions;
import com.origins.domain.tables.Roles;
import com.origins.domain.tables.Staff;
import com.origins.domain.tables.Students;
import com.origins.domain.tables.UserHasPermissions;
import com.origins.domain.tables.UserHasRoles;
import com.origins.domain.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SrrsTsd extends SchemaImpl {

    private static final long serialVersionUID = 1981035826;

    /**
     * The reference instance of <code>srrs_tsd</code>
     */
    public static final SrrsTsd SRRS_TSD = new SrrsTsd();

    /**
     * The table <code>srrs_tsd.availabilities</code>.
     */
    public final Availabilities AVAILABILITIES = Availabilities.AVAILABILITIES;

    /**
     * The table <code>srrs_tsd.categories</code>.
     */
    public final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>srrs_tsd.migrations</code>.
     */
    public final Migrations MIGRATIONS = Migrations.MIGRATIONS;

    /**
     * The table <code>srrs_tsd.password_resets</code>.
     */
    public final PasswordResets PASSWORD_RESETS = PasswordResets.PASSWORD_RESETS;

    /**
     * The table <code>srrs_tsd.permissions</code>.
     */
    public final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>srrs_tsd.reservations</code>.
     */
    public final Reservations RESERVATIONS = Reservations.RESERVATIONS;

    /**
     * The table <code>srrs_tsd.resources</code>.
     */
    public final Resources RESOURCES = Resources.RESOURCES;

    /**
     * The table <code>srrs_tsd.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>srrs_tsd.role_has_permissions</code>.
     */
    public final RoleHasPermissions ROLE_HAS_PERMISSIONS = RoleHasPermissions.ROLE_HAS_PERMISSIONS;

    /**
     * The table <code>srrs_tsd.staff</code>.
     */
    public final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>srrs_tsd.students</code>.
     */
    public final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>srrs_tsd.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>srrs_tsd.user_has_permissions</code>.
     */
    public final UserHasPermissions USER_HAS_PERMISSIONS = UserHasPermissions.USER_HAS_PERMISSIONS;

    /**
     * The table <code>srrs_tsd.user_has_roles</code>.
     */
    public final UserHasRoles USER_HAS_ROLES = UserHasRoles.USER_HAS_ROLES;

    /**
     * No further instances allowed
     */
    private SrrsTsd() {
        super("srrs_tsd", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Availabilities.AVAILABILITIES,
            Categories.CATEGORIES,
            Migrations.MIGRATIONS,
            PasswordResets.PASSWORD_RESETS,
            Permissions.PERMISSIONS,
            Reservations.RESERVATIONS,
            Resources.RESOURCES,
            Roles.ROLES,
            RoleHasPermissions.ROLE_HAS_PERMISSIONS,
            Staff.STAFF,
            Students.STUDENTS,
            Users.USERS,
            UserHasPermissions.USER_HAS_PERMISSIONS,
            UserHasRoles.USER_HAS_ROLES);
    }
}
