/*
 * This file is generated by jOOQ.
*/
package com.origins.domain;


import com.origins.domain.tables.Availabilities;
import com.origins.domain.tables.Categories;
import com.origins.domain.tables.Migrations;
import com.origins.domain.tables.PasswordResets;
import com.origins.domain.tables.Reservations;
import com.origins.domain.tables.Resources;
import com.origins.domain.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in tsd_srrs
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tsd_srrs.availabilities</code>.
     */
    public static final Availabilities AVAILABILITIES = com.origins.domain.tables.Availabilities.AVAILABILITIES;

    /**
     * The table <code>tsd_srrs.categories</code>.
     */
    public static final Categories CATEGORIES = com.origins.domain.tables.Categories.CATEGORIES;

    /**
     * The table <code>tsd_srrs.migrations</code>.
     */
    public static final Migrations MIGRATIONS = com.origins.domain.tables.Migrations.MIGRATIONS;

    /**
     * The table <code>tsd_srrs.password_resets</code>.
     */
    public static final PasswordResets PASSWORD_RESETS = com.origins.domain.tables.PasswordResets.PASSWORD_RESETS;

    /**
     * The table <code>tsd_srrs.reservations</code>.
     */
    public static final Reservations RESERVATIONS = com.origins.domain.tables.Reservations.RESERVATIONS;

    /**
     * The table <code>tsd_srrs.resources</code>.
     */
    public static final Resources RESOURCES = com.origins.domain.tables.Resources.RESOURCES;

    /**
     * The table <code>tsd_srrs.user</code>.
     */
    public static final User USER = com.origins.domain.tables.User.USER;
}
