/*
 * This file is generated by jOOQ.
*/
package com.origins.domain;


import com.origins.domain.tables.Availabilities;
import com.origins.domain.tables.Categories;
import com.origins.domain.tables.Migrations;
import com.origins.domain.tables.PasswordResets;
import com.origins.domain.tables.Permissions;
import com.origins.domain.tables.Reservations;
import com.origins.domain.tables.Resources;
import com.origins.domain.tables.RoleHasPermissions;
import com.origins.domain.tables.Roles;
import com.origins.domain.tables.Staff;
import com.origins.domain.tables.Students;
import com.origins.domain.tables.UserHasPermissions;
import com.origins.domain.tables.UserHasRoles;
import com.origins.domain.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in tsd_srrs
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tsd_srrs.availabilities</code>.
     */
    public static final Availabilities AVAILABILITIES = com.origins.domain.tables.Availabilities.AVAILABILITIES;

    /**
     * The table <code>tsd_srrs.categories</code>.
     */
    public static final Categories CATEGORIES = com.origins.domain.tables.Categories.CATEGORIES;

    /**
     * The table <code>tsd_srrs.migrations</code>.
     */
    public static final Migrations MIGRATIONS = com.origins.domain.tables.Migrations.MIGRATIONS;

    /**
     * The table <code>tsd_srrs.password_resets</code>.
     */
    public static final PasswordResets PASSWORD_RESETS = com.origins.domain.tables.PasswordResets.PASSWORD_RESETS;

    /**
     * The table <code>tsd_srrs.permissions</code>.
     */
    public static final Permissions PERMISSIONS = com.origins.domain.tables.Permissions.PERMISSIONS;

    /**
     * The table <code>tsd_srrs.reservations</code>.
     */
    public static final Reservations RESERVATIONS = com.origins.domain.tables.Reservations.RESERVATIONS;

    /**
     * The table <code>tsd_srrs.resources</code>.
     */
    public static final Resources RESOURCES = com.origins.domain.tables.Resources.RESOURCES;

    /**
     * The table <code>tsd_srrs.roles</code>.
     */
    public static final Roles ROLES = com.origins.domain.tables.Roles.ROLES;

    /**
     * The table <code>tsd_srrs.role_has_permissions</code>.
     */
    public static final RoleHasPermissions ROLE_HAS_PERMISSIONS = com.origins.domain.tables.RoleHasPermissions.ROLE_HAS_PERMISSIONS;

    /**
     * The table <code>tsd_srrs.staff</code>.
     */
    public static final Staff STAFF = com.origins.domain.tables.Staff.STAFF;

    /**
     * The table <code>tsd_srrs.students</code>.
     */
    public static final Students STUDENTS = com.origins.domain.tables.Students.STUDENTS;

    /**
     * The table <code>tsd_srrs.users</code>.
     */
    public static final Users USERS = com.origins.domain.tables.Users.USERS;

    /**
     * The table <code>tsd_srrs.user_has_permissions</code>.
     */
    public static final UserHasPermissions USER_HAS_PERMISSIONS = com.origins.domain.tables.UserHasPermissions.USER_HAS_PERMISSIONS;

    /**
     * The table <code>tsd_srrs.user_has_roles</code>.
     */
    public static final UserHasRoles USER_HAS_ROLES = com.origins.domain.tables.UserHasRoles.USER_HAS_ROLES;
}
