/*
 * This file is generated by jOOQ.
*/
package com.origins.domain;


import com.origins.domain.tables.Availabilities;
import com.origins.domain.tables.Categories;
import com.origins.domain.tables.Migrations;
import com.origins.domain.tables.PasswordResets;
import com.origins.domain.tables.Permissions;
import com.origins.domain.tables.Reservations;
import com.origins.domain.tables.Resources;
import com.origins.domain.tables.RoleHasPermissions;
import com.origins.domain.tables.Roles;
import com.origins.domain.tables.Staff;
import com.origins.domain.tables.Students;
import com.origins.domain.tables.UserHasPermissions;
import com.origins.domain.tables.UserHasRoles;
import com.origins.domain.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in srrs_tsd
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>srrs_tsd.availabilities</code>.
     */
    public static final Availabilities AVAILABILITIES = Availabilities.AVAILABILITIES;

    /**
     * The table <code>srrs_tsd.categories</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>srrs_tsd.migrations</code>.
     */
    public static final Migrations MIGRATIONS = Migrations.MIGRATIONS;

    /**
     * The table <code>srrs_tsd.password_resets</code>.
     */
    public static final PasswordResets PASSWORD_RESETS = PasswordResets.PASSWORD_RESETS;

    /**
     * The table <code>srrs_tsd.permissions</code>.
     */
    public static final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>srrs_tsd.reservations</code>.
     */
    public static final Reservations RESERVATIONS = Reservations.RESERVATIONS;

    /**
     * The table <code>srrs_tsd.resources</code>.
     */
    public static final Resources RESOURCES = Resources.RESOURCES;

    /**
     * The table <code>srrs_tsd.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>srrs_tsd.role_has_permissions</code>.
     */
    public static final RoleHasPermissions ROLE_HAS_PERMISSIONS = RoleHasPermissions.ROLE_HAS_PERMISSIONS;

    /**
     * The table <code>srrs_tsd.staff</code>.
     */
    public static final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>srrs_tsd.students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>srrs_tsd.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>srrs_tsd.user_has_permissions</code>.
     */
    public static final UserHasPermissions USER_HAS_PERMISSIONS = UserHasPermissions.USER_HAS_PERMISSIONS;

    /**
     * The table <code>srrs_tsd.user_has_roles</code>.
     */
    public static final UserHasRoles USER_HAS_ROLES = UserHasRoles.USER_HAS_ROLES;
}
