/*
 * This file is generated by jOOQ.
*/
package com.origins.domain;


import com.origins.DefaultCatalog;
import com.origins.domain.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TsdSrrs extends SchemaImpl {

    private static final long serialVersionUID = 352944105;

    /**
     * The reference instance of <code>tsd_srrs</code>
     */
    public static final TsdSrrs TSD_SRRS = new TsdSrrs();

    /**
     * The table <code>tsd_srrs.availabilities</code>.
     */
    public final Availabilities AVAILABILITIES = com.origins.domain.tables.Availabilities.AVAILABILITIES;

    /**
     * The table <code>tsd_srrs.categories</code>.
     */
    public final Categories CATEGORIES = com.origins.domain.tables.Categories.CATEGORIES;

    /**
     * The table <code>tsd_srrs.migrations</code>.
     */
    public final Migrations MIGRATIONS = com.origins.domain.tables.Migrations.MIGRATIONS;

    /**
     * The table <code>tsd_srrs.password_resets</code>.
     */
    public final PasswordResets PASSWORD_RESETS = com.origins.domain.tables.PasswordResets.PASSWORD_RESETS;

    /**
     * The table <code>tsd_srrs.reservations</code>.
     */
    public final Reservations RESERVATIONS = com.origins.domain.tables.Reservations.RESERVATIONS;

    /**
     * The table <code>tsd_srrs.resources</code>.
     */
    public final Resources RESOURCES = com.origins.domain.tables.Resources.RESOURCES;

    /**
     * The table <code>tsd_srrs.user</code>.
     */
    public final User USER = com.origins.domain.tables.User.USER;

    /**
     * No further instances allowed
     */
    private TsdSrrs() {
        super("tsd_srrs", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Availabilities.AVAILABILITIES,
            Categories.CATEGORIES,
            Migrations.MIGRATIONS,
            PasswordResets.PASSWORD_RESETS,
            Reservations.RESERVATIONS,
            Resources.RESOURCES,
            User.USER);
    }
}
