/*
 * This file is generated by jOOQ.
*/
package com.origins.domain.tables;


import com.origins.domain.Keys;
import com.origins.domain.TsdSrrs;
import com.origins.domain.tables.records.AvailabilitiesRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Availabilities extends TableImpl<AvailabilitiesRecord> {

    private static final long serialVersionUID = -971722558;

    /**
     * The reference instance of <code>tsd_srrs.availabilities</code>
     */
    public static final Availabilities AVAILABILITIES = new Availabilities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AvailabilitiesRecord> getRecordType() {
        return AvailabilitiesRecord.class;
    }

    /**
     * The column <code>tsd_srrs.availabilities.id</code>.
     */
    public final TableField<AvailabilitiesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tsd_srrs.availabilities.resource_id</code>.
     */
    public final TableField<AvailabilitiesRecord, UInteger> RESOURCE_ID = createField("resource_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>tsd_srrs.availabilities.start</code>.
     */
    public final TableField<AvailabilitiesRecord, Timestamp> START = createField("start", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>tsd_srrs.availabilities.end</code>.
     */
    public final TableField<AvailabilitiesRecord, Timestamp> END = createField("end", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>tsd_srrs.availabilities.created_at</code>.
     */
    public final TableField<AvailabilitiesRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>tsd_srrs.availabilities.updated_at</code>.
     */
    public final TableField<AvailabilitiesRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>tsd_srrs.availabilities</code> table reference
     */
    public Availabilities() {
        this("availabilities", null);
    }

    /**
     * Create an aliased <code>tsd_srrs.availabilities</code> table reference
     */
    public Availabilities(String alias) {
        this(alias, AVAILABILITIES);
    }

    private Availabilities(String alias, Table<AvailabilitiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Availabilities(String alias, Table<AvailabilitiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return TsdSrrs.TSD_SRRS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AvailabilitiesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_AVAILABILITIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AvailabilitiesRecord> getPrimaryKey() {
        return Keys.KEY_AVAILABILITIES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AvailabilitiesRecord>> getKeys() {
        return Arrays.<UniqueKey<AvailabilitiesRecord>>asList(Keys.KEY_AVAILABILITIES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AvailabilitiesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AvailabilitiesRecord, ?>>asList(Keys.AVAILABILITIES_RESOURCE_ID_FOREIGN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Availabilities as(String alias) {
        return new Availabilities(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Availabilities rename(String name) {
        return new Availabilities(name, null);
    }
}
