/*
 * This file is generated by jOOQ.
*/
package com.origins.domain.tables;


import com.origins.domain.Keys;
import com.origins.domain.SrrsTsd;
import com.origins.domain.tables.records.RoleHasPermissionsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleHasPermissions extends TableImpl<RoleHasPermissionsRecord> {

    private static final long serialVersionUID = -184775938;

    /**
     * The reference instance of <code>srrs_tsd.role_has_permissions</code>
     */
    public static final RoleHasPermissions ROLE_HAS_PERMISSIONS = new RoleHasPermissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoleHasPermissionsRecord> getRecordType() {
        return RoleHasPermissionsRecord.class;
    }

    /**
     * The column <code>srrs_tsd.role_has_permissions.permission_id</code>.
     */
    public final TableField<RoleHasPermissionsRecord, UInteger> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>srrs_tsd.role_has_permissions.role_id</code>.
     */
    public final TableField<RoleHasPermissionsRecord, UInteger> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>srrs_tsd.role_has_permissions</code> table reference
     */
    public RoleHasPermissions() {
        this("role_has_permissions", null);
    }

    /**
     * Create an aliased <code>srrs_tsd.role_has_permissions</code> table reference
     */
    public RoleHasPermissions(String alias) {
        this(alias, ROLE_HAS_PERMISSIONS);
    }

    private RoleHasPermissions(String alias, Table<RoleHasPermissionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoleHasPermissions(String alias, Table<RoleHasPermissionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SrrsTsd.SRRS_TSD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoleHasPermissionsRecord> getPrimaryKey() {
        return Keys.KEY_ROLE_HAS_PERMISSIONS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoleHasPermissionsRecord>> getKeys() {
        return Arrays.<UniqueKey<RoleHasPermissionsRecord>>asList(Keys.KEY_ROLE_HAS_PERMISSIONS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RoleHasPermissionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoleHasPermissionsRecord, ?>>asList(Keys.ROLE_HAS_PERMISSIONS_PERMISSION_ID_FOREIGN, Keys.ROLE_HAS_PERMISSIONS_ROLE_ID_FOREIGN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleHasPermissions as(String alias) {
        return new RoleHasPermissions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleHasPermissions rename(String name) {
        return new RoleHasPermissions(name, null);
    }
}
