/*
 * This file is generated by jOOQ.
*/
package com.origins.domain.tables.records;


import com.origins.domain.tables.Availabilities;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvailabilitiesRecord extends UpdatableRecordImpl<AvailabilitiesRecord> implements Record6<UInteger, UInteger, Timestamp, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -90526590;

    /**
     * Setter for <code>tsd_srrs.availabilities.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>tsd_srrs.availabilities.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>tsd_srrs.availabilities.resource_id</code>.
     */
    public void setResourceId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>tsd_srrs.availabilities.resource_id</code>.
     */
    public UInteger getResourceId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>tsd_srrs.availabilities.start</code>.
     */
    public void setStart(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>tsd_srrs.availabilities.start</code>.
     */
    public Timestamp getStart() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>tsd_srrs.availabilities.end</code>.
     */
    public void setEnd(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>tsd_srrs.availabilities.end</code>.
     */
    public Timestamp getEnd() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>tsd_srrs.availabilities.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>tsd_srrs.availabilities.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>tsd_srrs.availabilities.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>tsd_srrs.availabilities.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, Timestamp, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, Timestamp, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Availabilities.AVAILABILITIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Availabilities.AVAILABILITIES.RESOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Availabilities.AVAILABILITIES.START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Availabilities.AVAILABILITIES.END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Availabilities.AVAILABILITIES.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Availabilities.AVAILABILITIES.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilitiesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilitiesRecord value2(UInteger value) {
        setResourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilitiesRecord value3(Timestamp value) {
        setStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilitiesRecord value4(Timestamp value) {
        setEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilitiesRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilitiesRecord value6(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AvailabilitiesRecord values(UInteger value1, UInteger value2, Timestamp value3, Timestamp value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AvailabilitiesRecord
     */
    public AvailabilitiesRecord() {
        super(Availabilities.AVAILABILITIES);
    }

    /**
     * Create a detached, initialised AvailabilitiesRecord
     */
    public AvailabilitiesRecord(UInteger id, UInteger resourceId, Timestamp start, Timestamp end, Timestamp createdAt, Timestamp updatedAt) {
        super(Availabilities.AVAILABILITIES);

        set(0, id);
        set(1, resourceId);
        set(2, start);
        set(3, end);
        set(4, createdAt);
        set(5, updatedAt);
    }
}
