/*
 * This file is generated by jOOQ.
*/
package com.origins.domain.tables.records;


import com.origins.domain.tables.Reservations;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReservationsRecord extends UpdatableRecordImpl<ReservationsRecord> implements Record13<UInteger, UInteger, String, String, String, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1381279955;

    /**
     * Setter for <code>srrs_tsd.reservations.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.resource_id</code>.
     */
    public void setResourceId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.resource_id</code>.
     */
    public UInteger getResourceId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.user_id</code>.
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.purpose</code>.
     */
    public void setPurpose(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.purpose</code>.
     */
    public String getPurpose() {
        return (String) get(3);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.address</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.address</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.nic_number</code>.
     */
    public void setNicNumber(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.nic_number</code>.
     */
    public String getNicNumber() {
        return (String) get(6);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.conact_number</code>.
     */
    public void setConactNumber(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.conact_number</code>.
     */
    public String getConactNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.email_address</code>.
     */
    public void setEmailAddress(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.email_address</code>.
     */
    public String getEmailAddress() {
        return (String) get(8);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.start</code>.
     */
    public void setStart(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.start</code>.
     */
    public Timestamp getStart() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.end</code>.
     */
    public void setEnd(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.end</code>.
     */
    public Timestamp getEnd() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>srrs_tsd.reservations.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>srrs_tsd.reservations.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<UInteger, UInteger, String, String, String, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<UInteger, UInteger, String, String, String, String, String, String, String, Timestamp, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Reservations.RESERVATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Reservations.RESERVATIONS.RESOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Reservations.RESERVATIONS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Reservations.RESERVATIONS.PURPOSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Reservations.RESERVATIONS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Reservations.RESERVATIONS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Reservations.RESERVATIONS.NIC_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Reservations.RESERVATIONS.CONACT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Reservations.RESERVATIONS.EMAIL_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Reservations.RESERVATIONS.START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Reservations.RESERVATIONS.END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Reservations.RESERVATIONS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Reservations.RESERVATIONS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPurpose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNicNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getConactNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value2(UInteger value) {
        setResourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value3(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value4(String value) {
        setPurpose(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value5(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value6(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value7(String value) {
        setNicNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value8(String value) {
        setConactNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value9(String value) {
        setEmailAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value10(Timestamp value) {
        setStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value11(Timestamp value) {
        setEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value12(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord value13(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationsRecord values(UInteger value1, UInteger value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Timestamp value10, Timestamp value11, Timestamp value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservationsRecord
     */
    public ReservationsRecord() {
        super(Reservations.RESERVATIONS);
    }

    /**
     * Create a detached, initialised ReservationsRecord
     */
    public ReservationsRecord(UInteger id, UInteger resourceId, String userId, String purpose, String name, String address, String nicNumber, String conactNumber, String emailAddress, Timestamp start, Timestamp end, Timestamp createdAt, Timestamp updatedAt) {
        super(Reservations.RESERVATIONS);

        set(0, id);
        set(1, resourceId);
        set(2, userId);
        set(3, purpose);
        set(4, name);
        set(5, address);
        set(6, nicNumber);
        set(7, conactNumber);
        set(8, emailAddress);
        set(9, start);
        set(10, end);
        set(11, createdAt);
        set(12, updatedAt);
    }
}
