/*
 * This file is generated by jOOQ.
*/
package com.origins.domain.tables.records;


import com.origins.domain.tables.Students;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentsRecord extends UpdatableRecordImpl<StudentsRecord> implements Record11<UInteger, String, UInteger, String, Timestamp, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 2044483309;

    /**
     * Setter for <code>tsd_srrs.students.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>tsd_srrs.students.reg_id</code>.
     */
    public void setRegId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.reg_id</code>.
     */
    public String getRegId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tsd_srrs.students.pin</code>.
     */
    public void setPin(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.pin</code>.
     */
    public UInteger getPin() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>tsd_srrs.students.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tsd_srrs.students.date_of_birth</code>.
     */
    public void setDateOfBirth(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.date_of_birth</code>.
     */
    public Timestamp getDateOfBirth() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>tsd_srrs.students.address</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.address</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tsd_srrs.students.email_address</code>.
     */
    public void setEmailAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.email_address</code>.
     */
    public String getEmailAddress() {
        return (String) get(6);
    }

    /**
     * Setter for <code>tsd_srrs.students.contact_number</code>.
     */
    public void setContactNumber(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.contact_number</code>.
     */
    public String getContactNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>tsd_srrs.students.class</code>.
     */
    public void setClass_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.class</code>.
     */
    public String getClass_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>tsd_srrs.students.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>tsd_srrs.students.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>tsd_srrs.students.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<UInteger, String, UInteger, String, Timestamp, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<UInteger, String, UInteger, String, Timestamp, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Students.STUDENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Students.STUDENTS.REG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return Students.STUDENTS.PIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Students.STUDENTS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Students.STUDENTS.DATE_OF_BIRTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Students.STUDENTS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Students.STUDENTS.EMAIL_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Students.STUDENTS.CONTACT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Students.STUDENTS.CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Students.STUDENTS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Students.STUDENTS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRegId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getPin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDateOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getContactNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getClass_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value2(String value) {
        setRegId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value3(UInteger value) {
        setPin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value5(Timestamp value) {
        setDateOfBirth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value6(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value7(String value) {
        setEmailAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value8(String value) {
        setContactNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value9(String value) {
        setClass_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value10(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord value11(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentsRecord values(UInteger value1, String value2, UInteger value3, String value4, Timestamp value5, String value6, String value7, String value8, String value9, Timestamp value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentsRecord
     */
    public StudentsRecord() {
        super(Students.STUDENTS);
    }

    /**
     * Create a detached, initialised StudentsRecord
     */
    public StudentsRecord(UInteger id, String regId, UInteger pin, String name, Timestamp dateOfBirth, String address, String emailAddress, String contactNumber, String class_, Timestamp createdAt, Timestamp updatedAt) {
        super(Students.STUDENTS);

        set(0, id);
        set(1, regId);
        set(2, pin);
        set(3, name);
        set(4, dateOfBirth);
        set(5, address);
        set(6, emailAddress);
        set(7, contactNumber);
        set(8, class_);
        set(9, createdAt);
        set(10, updatedAt);
    }
}
