/*
 * This file is generated by jOOQ.
*/
package com.origins.domain.tables.records;


import com.origins.domain.tables.UserHasRoles;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserHasRolesRecord extends UpdatableRecordImpl<UserHasRolesRecord> implements Record2<UInteger, UInteger> {

    private static final long serialVersionUID = -577795026;

    /**
     * Setter for <code>srrs_tsd.user_has_roles.role_id</code>.
     */
    public void setRoleId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>srrs_tsd.user_has_roles.role_id</code>.
     */
    public UInteger getRoleId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>srrs_tsd.user_has_roles.user_id</code>.
     */
    public void setUserId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>srrs_tsd.user_has_roles.user_id</code>.
     */
    public UInteger getUserId() {
        return (UInteger) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, UInteger> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, UInteger> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return UserHasRoles.USER_HAS_ROLES.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return UserHasRoles.USER_HAS_ROLES.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserHasRolesRecord value1(UInteger value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserHasRolesRecord value2(UInteger value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserHasRolesRecord values(UInteger value1, UInteger value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserHasRolesRecord
     */
    public UserHasRolesRecord() {
        super(UserHasRoles.USER_HAS_ROLES);
    }

    /**
     * Create a detached, initialised UserHasRolesRecord
     */
    public UserHasRolesRecord(UInteger roleId, UInteger userId) {
        super(UserHasRoles.USER_HAS_ROLES);

        set(0, roleId);
        set(1, userId);
    }
}
